#!/usr/bin/env python3
"""Response-pool manifests: bind every judged response to the checkpoint that made it.

Training used to take learner and reference responses as bare file paths. Nothing
tied those files to the proximal centre ``pi_t`` or to the reference policy
``mu``, so a stale pool -- decoded from a different checkpoint, or from a
different prompt file with the same ids -- was indistinguishable from the right
one. A manifest records the content fingerprint of the generating checkpoint,
the exact prompt file and per-prompt text hashes, the decode parameters, and the
sha256 of every response file; the stage runner then requires

    learner pool fingerprint   == parent pi_t fingerprint
    reference pool fingerprint == configured mu fingerprint
    (at t = 0)  parent fingerprint == mu fingerprint

and exact -- never intersected -- prompt-set equality across every seed file.

Roles are distinct because their bindings are: ``learner_pool`` is generated by
``pi_t``, ``reference_comparator_pool`` by ``mu``, and
``monitoring_candidate_pool`` by the freshly trained candidate.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from mnpo_scripts.precompute_provenance import checkpoint_fingerprint, sha256_file_hex
from scripts.nbpo.nbpo_common import sha256_text, write_json

MANIFEST_SCHEMA_VERSION = 1
ROLES = ("learner_pool", "reference_comparator_pool", "monitoring_candidate_pool",
         # The monitoring comparators are mu's responses on the held-out prompts.
         # They were bare paths, so the Algorithm-1 gate could score the candidate
         # against stale comparators, or ones decoded from a different checkpoint.
         "monitoring_reference_comparator_pool")


def prompt_text_hashes(prompt_rows) -> dict:
    """``{prompt_id: sha256(prompt text)}`` -- ids alone never identify a prompt set."""
    return {str(pid): sha256_text(str(text)) for pid, text in prompt_rows}


def load_prompt_rows(path: Path):
    """(prompt_id, prompt) from a jsonl of {prompt[, prompt_id]}; duplicate ids raise."""
    rows = []
    for i, line in enumerate(Path(path).read_text().splitlines()):
        if not line.strip():
            continue
        d = json.loads(line)
        rows.append((str(d.get("prompt_id", i)), d["prompt"]))
    ids = [pid for pid, _ in rows]
    if len(set(ids)) != len(ids):
        dup = sorted({p for p in ids if ids.count(p) > 1})
        raise ValueError(f"duplicate prompt ids in {path}: {dup[:10]}")
    return rows



def check_row_prompts(rows, canonical_prompt_hashes: dict, what: str,
                      reproduction_mode: bool = True) -> None:
    """``sha256(row["prompt"]) == prompt_text_sha256[row["prompt_id"]]`` for every row.

    Ids are not prompts. Two files can carry identical ids and different prompt
    text, and every hash the manifest previously recorded would still match. A
    missing ``prompt`` field is a hard error in reproduction mode rather than a
    skipped check.
    """
    problems = []
    for r in rows:
        pid = str(r.get("prompt_id"))
        if "prompt" not in r:
            if reproduction_mode:
                problems.append(f"row {pid} has no 'prompt' field")
            continue
        want = canonical_prompt_hashes.get(pid)
        if want is None:
            problems.append(f"row {pid} is not in the canonical prompt set")
            continue
        got = sha256_text(str(r["prompt"]))
        if got != want:
            problems.append(f"row {pid} prompt text {got[:12]} != canonical {want[:12]}")
    if problems:
        raise ValueError(f"{what}: response rows do not match the canonical prompts: "
                         + "; ".join(problems[:8])
                         + (f" (+{len(problems) - 8} more)" if len(problems) > 8 else ""))


def build_manifest(role: str, checkpoint: str, prompts_file, prompt_rows, seeds,
                   response_files: dict, decode_params: dict,
                   chat_template_kwargs: dict = None, model_revision=None,
                   tokenizer_revision=None) -> dict:
    """Assemble a response-pool manifest; every file is hashed as it is recorded."""
    if role not in ROLES:
        raise ValueError(f"role must be one of {ROLES}, got {role!r}")
    prompt_rows = list(prompt_rows)
    canonical = prompt_text_hashes(prompt_rows)
    outputs = {}
    for seed, path in sorted(response_files.items(), key=lambda kv: str(kv[0])):
        p = Path(path)
        rows = json.loads(p.read_text())
        # A response row carries the prompt it was decoded from. Hashing only the
        # prompt FILE and the response file leaves the pairing unverified: a row
        # can carry a different prompt under the right id, and the pool then
        # answers a question the tensor does not describe.
        check_row_prompts(rows, canonical, f"{role} seed {seed} ({p})",
                          reproduction_mode=True)
        outputs[str(seed)] = {
            "path": str(p),
            "sha256": sha256_file_hex(str(p)),
            "n_rows": len(rows),
            "response_ids": sorted({str(r["prompt_id"]) for r in rows}),
            "row_prompt_sha256": {str(r["prompt_id"]): sha256_text(str(r["prompt"]))
                                  for r in rows},
        }
    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "role": role,
        "checkpoint": str(checkpoint),
        "checkpoint_fingerprint": checkpoint_fingerprint(str(checkpoint)),
        "model_revision": model_revision,
        "tokenizer_revision": tokenizer_revision,
        "prompts_file": str(prompts_file),
        "prompt_file_sha256": sha256_file_hex(str(prompts_file)),
        "prompt_ids": sorted(str(pid) for pid, _ in prompt_rows),
        "prompt_text_sha256": prompt_text_hashes(prompt_rows),
        "seeds": [str(s) for s in seeds],
        "decode_params": dict(decode_params),
        "chat_template_kwargs": dict(chat_template_kwargs or {}),
        "outputs": outputs,
    }


def _resolve_output_path(manifest_path, entry_path: str) -> Path:
    """Relative response paths resolve against the MANIFEST's directory, not the cwd."""
    p = Path(entry_path)
    return p if p.is_absolute() else (Path(manifest_path).resolve().parent / p)


def verify_manifest(manifest_path, expected_role: str, expected_fingerprint: str = None,
                    expected_prompt_ids=None, expected_prompt_text_sha256: dict = None,
                    expected_prompts_file=None, required_seeds=None,
                    expected_decode_params: dict = None,
                    expected_chat_template_kwargs: dict = None,
                    allow_partial_prompt_intersection: bool = False) -> dict:
    """Verify one manifest against everything the caller knows; return ``{seed: path}``.

    Every comparison is exact equality. Seeds especially: subset inclusion would
    silently accept a pool missing a seed, which changes the response
    cardinality and therefore the game. ``allow_partial_prompt_intersection`` is
    a diagnostic-only escape hatch and is never set in reproduction mode.
    """
    manifest_path = Path(manifest_path)
    man = json.loads(manifest_path.read_text())
    problems = []
    if man.get("role") != expected_role:
        problems.append(f"role={man.get('role')!r}, expected {expected_role!r}")
    if expected_fingerprint is not None and man.get("checkpoint_fingerprint") != expected_fingerprint:
        problems.append(
            f"checkpoint_fingerprint={str(man.get('checkpoint_fingerprint'))[:12]} != "
            f"expected {expected_fingerprint[:12]} (the pool was generated by a "
            "different checkpoint)")
    if expected_prompts_file is not None:
        want = sha256_file_hex(str(expected_prompts_file))
        if man.get("prompt_file_sha256") != want:
            problems.append(
                f"prompt_file_sha256={str(man.get('prompt_file_sha256'))[:12]} != "
                f"{want[:12]} (a different prompt file, even if the ids match)")
    if expected_prompt_ids is not None:
        have, want = set(man.get("prompt_ids") or []), {str(p) for p in expected_prompt_ids}
        if have != want and not allow_partial_prompt_intersection:
            problems.append(
                f"prompt ids differ: missing={sorted(want - have)[:5]} "
                f"unexpected={sorted(have - want)[:5]}")
    if expected_prompt_text_sha256:
        recorded = man.get("prompt_text_sha256") or {}
        bad = [pid for pid, h in expected_prompt_text_sha256.items()
               if recorded.get(pid) != h]
        if bad:
            problems.append(
                f"prompt TEXT differs for {len(bad)} ids (first {bad[:5]}): the pool was "
                "decoded from different prompts carrying the same ids")
    if required_seeds is not None:
        have, want = {str(s) for s in man.get("seeds") or []}, {str(s) for s in required_seeds}
        if have != want:
            problems.append(
                f"seeds must match exactly: missing={sorted(want - have)} "
                f"extra={sorted(have - want)}")
    if expected_decode_params:
        rec = man.get("decode_params") or {}
        bad = {k: (rec.get(k), v) for k, v in expected_decode_params.items()
               if rec.get(k) != v}
        if bad:
            problems.append(f"decode params differ (recorded, expected): {bad}")
    if expected_chat_template_kwargs is not None:
        rec = man.get("chat_template_kwargs") or {}
        if rec != dict(expected_chat_template_kwargs):
            problems.append(
                f"chat_template_kwargs={rec} != expected {dict(expected_chat_template_kwargs)}")
    paths = {}
    for seed, entry in sorted((man.get("outputs") or {}).items()):
        p = _resolve_output_path(manifest_path, entry["path"])
        if not p.exists():
            problems.append(f"response file for seed {seed} missing on disk: {p}")
            continue
        got = sha256_file_hex(str(p))
        if got != entry.get("sha256"):
            problems.append(
                f"response file {p} hash {got[:12]} != manifest {str(entry.get('sha256'))[:12]} "
                "(edited or replaced after generation)")
            continue
        rows = json.loads(p.read_text())
        ids = [str(r["prompt_id"]) for r in rows]
        if len(set(ids)) != len(ids):
            problems.append(f"duplicate prompt ids inside {p}")
        if expected_prompt_ids is not None and not allow_partial_prompt_intersection:
            have, want = set(ids), {str(x) for x in expected_prompt_ids}
            if have != want:
                problems.append(
                    f"seed {seed} prompt set differs: missing={sorted(want - have)[:5]} "
                    f"unexpected={sorted(have - want)[:5]}")
        empties = [str(r["prompt_id"]) for r in rows if not str(r.get("generated_text", "")).strip()]
        if empties:
            problems.append(f"seed {seed} has {len(empties)} empty responses (first {empties[:5]})")
        # Every row's prompt text must be the canonical one for its id.
        canonical = expected_prompt_text_sha256 or man.get("prompt_text_sha256") or {}
        if canonical:
            try:
                check_row_prompts(rows, canonical, f"seed {seed} ({p})",
                                  reproduction_mode=not allow_partial_prompt_intersection)
            except ValueError as e:
                problems.append(str(e))
        paths[str(seed)] = str(p)
    if problems:
        raise ValueError(f"response-pool manifest {manifest_path} failed verification: "
                         + "; ".join(problems))
    return {"seed_files": paths, "manifest": man,
            "manifest_sha256": sha256_file_hex(str(manifest_path))}


def write_manifest(path, manifest: dict) -> str:
    write_json(Path(path), manifest)
    return sha256_file_hex(str(path))


def check_stage_zero_identity(parent_fingerprint: str, mu_fingerprint: str, stage: int) -> None:
    """At t = 0 the proximal centre IS the reference policy; different weights are a bug."""
    if int(stage) == 0 and parent_fingerprint != mu_fingerprint:
        raise ValueError(
            "stage 0 requires pi_0 == mu, but the parent and reference checkpoints have "
            f"different content fingerprints: parent={parent_fingerprint[:12]} "
            f"mu={mu_fingerprint[:12]}")


def pool_manifest_summary(binding: dict) -> dict:
    """The compact block a stage record embeds for one verified pool."""
    man = binding["manifest"]
    return {k: man.get(k) for k in
            ("role", "checkpoint", "checkpoint_fingerprint", "prompt_file_sha256",
             "seeds", "decode_params", "chat_template_kwargs")} | {
        "manifest_sha256": binding["manifest_sha256"],
        "n_prompts": len(man.get("prompt_ids") or []),
    }
