#!/usr/bin/env python3
"""Build the reproduction-mode integration fixture: pools, manifests, checkpoints.

Everything is tiny and CPU-only, but the geometry is the manuscript's: four
learner responses, four comparator responses, six unordered pairs, both
presentation orders. The checkpoints are marker directories -- real enough for
``checkpoint_fingerprint`` to bind pools to them, which is what the manifests
test.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from scripts.nbpo.response_manifest import build_manifest, write_manifest  # noqa: E402

TRAIN = [f"t{i:02d}" for i in range(6)]
MON = [f"m{i:02d}" for i in range(4)]
FINAL = [f"f{i:02d}" for i in range(3)]
SEEDS = ["s0", "s1", "s2", "s3"]
REF_SEEDS = ["r0", "r1", "r2", "r3"]
DECODE = {"temperature": 0.9, "top_p": 0.95, "max_new_tokens": 64}


def write_prompts(path: Path, ids):
    path.write_text("\n".join(json.dumps({"prompt_id": i, "prompt": f"prompt {i}"}) for i in ids)
                    + "\n")
    return [(i, f"prompt {i}") for i in ids]


def write_pool(path: Path, ids, seed: str, tag: str):
    path.write_text(json.dumps(
        [{"prompt_id": i, "prompt": f"prompt {i}",
          "generated_text": f"{tag}:{seed}:{i}: a response of length {len(i) + len(seed)}"}
         for i in ids], ensure_ascii=False))
    return path


def real_checkpoint(path: Path, identity: str) -> Path:
    """A loadable tiny checkpoint -- the manifests bind to its content fingerprint.

    It must exist in full BEFORE the manifests are written and before the stage
    runs: any file added later changes the fingerprint and would break exactly
    the history0 binding this fixture is meant to verify.
    """
    from tests.fixtures.nbpo_real.stubs.real_precompute import ensure_tiny_model

    ensure_tiny_model(path)
    (path / "MARKER.json").write_text(json.dumps({"identity": identity}))
    return path


def main(root: Path):
    assets = root / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    train_rows = write_prompts(assets / "train_prompts.jsonl", TRAIN)
    write_prompts(assets / "monitoring_prompts.jsonl", MON)
    write_prompts(assets / "final_eval_prompts.jsonl", FINAL)

    # At stage 0 the proximal centre IS the reference policy, so both pools are
    # generated by ONE checkpoint and the manifests must agree on its fingerprint.
    mu = real_checkpoint(assets / "checkpoints" / "mu", "mu==pi_0")
    learner_files = {s: str(write_pool(assets / f"train_policy_{s}.json", TRAIN, s, "pol"))
                     for s in SEEDS}
    ref_files = {r: str(write_pool(assets / f"train_ref_{r}.json", TRAIN, r, "ref"))
                 for r in REF_SEEDS}
    for r in REF_SEEDS:
        write_pool(assets / f"mon_ref_{r}.json", MON, r, "monref")

    write_manifest(assets / "learner_pool.json", build_manifest(
        "learner_pool", str(mu), assets / "train_prompts.jsonl", train_rows,
        SEEDS, learner_files, DECODE, chat_template_kwargs={}))
    write_manifest(assets / "reference_pool.json", build_manifest(
        "reference_comparator_pool", str(mu), assets / "train_prompts.jsonl", train_rows,
        REF_SEEDS, ref_files, DECODE, chat_template_kwargs={}))
    print(f"[nbpo_real] fixture written under {assets}")


if __name__ == "__main__":
    main(Path(__file__).resolve().parent)
