#!/usr/bin/env python3
"""Build the stronger-training validation table from measured artifacts."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


LABELS = {
    "base": "Base",
    "ronpo_full_expect": "RONPO (full-exp.)",
    "ronpo_k_only": "RONPO (top-mass)",
    "inpo_avg": "INPO (avg)",
    "sppo_avg": "SPPO (avg)",
}
ORDER = ("base", "ronpo_full_expect", "inpo_avg", "ronpo_k_only", "sppo_avg")
ROW_END = " " + chr(92) * 2


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--power-summary", type=Path, required=True)
    parser.add_argument("--raw-csv", type=Path, required=True)
    parser.add_argument("--gate-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    power = json.loads(args.power_summary.read_text())
    if power.get("status") != "completed" or power.get("split") != "non-sealed 128-prompt validation":
        raise RuntimeError("stronger validation summary is incomplete")
    if power.get("spent_sealed_split_touched") is not False:
        raise RuntimeError("spent sealed split integrity check failed")
    ranked = {row["model"]: row for row in power["normalized_ranking"]}
    with args.raw_csv.open(newline="", encoding="utf-8") as handle:
        raw_rows = list(csv.DictReader(handle))
    concise = {
        row["model"]: row for row in raw_rows if row["evaluator"] == "armo_conciseness"
    }
    gates = {
        model: json.loads((args.gate_dir / f"{model}.json").read_text()) for model in ORDER
    }
    if set(power["models"]) != set(ranked) or set(power["models"]) != set(concise):
        raise RuntimeError("eligible model set differs across measured artifacts")

    lines = [
        "% AUTO-GENERATED by build_stronger_validation_table.py; do not hand-edit numbers",
        "\\begin{table}[t]", "\\centering", "\\scriptsize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{lcrr}", "\\toprule",
        "Model & Gate & Worst (95\\% CI) & $\\Delta$ concise vs. base (95\\% CI)" + ROW_END,
        "\\midrule",
    ]
    for model in ORDER:
        gate = gates[model]
        if not gate["passed"]:
            repeat = int(gate["candidate"]["max_repeat_run"])
            lines.append(f"{LABELS[model]} & FAIL ({repeat}) & -- & --" + ROW_END)
            continue
        rank = ranked[model]
        raw = concise[model]
        worst = (
            f"{float(rank['mean_primary_prompt_worst_norm_score']):.4f} "
            f"[{float(rank['mean_primary_prompt_worst_norm_score_ci95_low']):.4f}, "
            f"{float(rank['mean_primary_prompt_worst_norm_score_ci95_high']):.4f}]"
        )
        if model == "base":
            delta = "--"
        else:
            delta = (
                f"{float(raw['mean_raw_delta_vs_base']):+.5f} "
                f"[{float(raw['mean_raw_delta_vs_base_ci95_low']):+.5f}, "
                f"{float(raw['mean_raw_delta_vs_base_ci95_high']):+.5f}]"
            )
        lines.append(f"{LABELS[model]} & PASS & {worst} & {delta}" + ROW_END)
    lines.extend([
        "\\bottomrule", "\\end{tabular}%", "}",
        "\\caption{\\textbf{Stronger-training power check} on the non-sealed 128-prompt validation split. All methods use 1,800 steps and seed 42. The gate is fail-closed; the number in parentheses is the maximum identical-word run for a failed model. Only full-expectation RONPO has a raw conciseness delta whose paired 95\\% bootstrap interval excludes zero, and the shift is negative. The base policy has the highest normalized worst-objective point estimate among the eligible models.}",
        "\\label{tab:qwen3-stronger-validation}", "\\end{table}", "",
    ])
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
