#!/usr/bin/env python3
"""Build the Qwen3 sealed open-weight pairwise appendix table from JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DISPLAY = {
    "base": "Base",
    "ronpo_k_only": "RONPO (top-mass)",
    "ronpo_full_expect": "RONPO (full-exp.)",
    "ipo": "IPO",
    "simpo": "SimPO",
    "sppo_avg": "SPPO (avg)",
    "inpo_avg": "INPO (avg)",
    "ht_mnpo_helpfulness": "HT-MNPO (help.)",
    "ht_mnpo_safety": "HT-MNPO (safety)",
    "ht_mnpo_conciseness": "HT-MNPO (concise)",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    payload = json.loads(args.summary.read_text())
    if payload.get("status") != "completed" or payload.get("num_judgments") != 27180:
        raise RuntimeError("independent judge summary is incomplete")
    ranked = payload["ranked"]
    lines = [
        r"% AUTO-GENERATED by build_sealed_pairwise_judge_table.py: do not hand-edit numbers",
        r"\begin{table}[t]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{rlrr}",
        r"\toprule",
        r"Rank & Method & Pairwise score (95\% CI) & WR$_{\mathrm{B}}$ \\",
        r"\midrule",
    ]
    for row in ranked:
        model = row["model"]
        name = DISPLAY[model]
        if model == "ronpo_k_only":
            name = r"\textbf{" + name + "}"
        score = 100 * float(row["mean_pairwise_score"])
        low = 100 * float(row["ci95_low"])
        high = 100 * float(row["ci95_high"])
        base = row.get("win_rate_vs_base")
        base_text = "--" if base is None else f"{100 * float(base):.2f}"
        lines.append(
            f"{int(row['rank'])} & {name} & {score:.2f} [{low:.2f}, {high:.2f}] & {base_text} " + r"\\"
        )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{\textbf{Reward-model-independent sealed pairwise diagnostic.} "
        r"A pinned open-weight \texttt{gpt-oss-120b} judge compares all eligible model pairs "
        r"on each of the 604 sealed prompts, with deterministic order randomization. The score "
        r"averages nine opponents per model and prompt; ties count as $0.5$. Intervals use 2,000 "
        r"prompt bootstrap resamples with seed 42. All 27,180 verdicts parsed successfully. "
        r"This is an open-weight diagnostic rather than an official closed-judge benchmark score; "
        r"DPO is absent because it failed the pre-reward stability gate.}",
        r"\label{tab:qwen3-sealed-pairwise}",
        r"\end{table}",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
