#!/usr/bin/env python3
"""Aggregate the preregistered diagnostic W2 estimator ablation.

All rows are normalized together with W1 and Base so the diagnostic curve is
comparable within this experiment.  The script never writes the W1 headline
gate or replaces its table.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


DISPLAY = {
    "base": "Base",
    "ronpo_os_confirmatory": "RONPO (OS, entropy 0.55; confirmatory)",
    "ronpo_topmass": "RONPO (top-mass endpoint; diagnostic)",
    "ronpo_uniform": "RONPO (uniform endpoint; diagnostic)",
    "ronpo_os_entropy_0p15_diagnostic": "RONPO (OS, entropy 0.15; diagnostic)",
    "ronpo_os_entropy_0p85_diagnostic": "RONPO (OS, entropy 0.85; diagnostic)",
    "mnpo": "MNPO (diagnostic)",
    "ronpo_os_lr_1e-6_diagnostic": "RONPO (OS, lr 1e-6; diagnostic)",
    "inpo_avg_lr_1e-6_fairness": "INPO (avg, lr 1e-6; diagnostic)",
    "ipo_lr_1e-6_fairness": "IPO (lr 1e-6; diagnostic)",
}
W2 = [
    "ronpo_topmass", "ronpo_uniform", "ronpo_os_entropy_0p15_diagnostic",
    "ronpo_os_entropy_0p85_diagnostic", "mnpo", "ronpo_os_lr_1e-6_diagnostic",
    "inpo_avg_lr_1e-6_fairness", "ipo_lr_1e-6_fairness",
]


def rows(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def ci(values: np.ndarray) -> tuple[float, float]:
    return float(np.quantile(values, .025)), float(np.quantile(values, .975))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--helpfulness", type=Path, required=True)
    ap.add_argument("--harmlessness", type=Path, required=True)
    ap.add_argument("--pool-audit", type=Path, required=True)
    ap.add_argument("--output-dir", type=Path, required=True)
    ap.add_argument("--bootstrap", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args(); args.output_dir.mkdir(parents=True, exist_ok=True)
    audit = json.loads(args.pool_audit.read_text(encoding="utf-8")); models = audit["eligible_models"]
    h = {str(r["prompt_id"]): r for r in rows(args.helpfulness)}
    s = {str(r["prompt_id"]): r for r in rows(args.harmlessness)}
    ids = sorted(h)
    if set(ids) != set(s) or not ids or models[0] != "base": raise RuntimeError("invalid scored model pool")
    raw = np.empty((len(ids), 2, len(models)))
    for i, key in enumerate(ids):
        for j, source in enumerate((h, s)):
            row = source[key]
            if row["response_model_names"] != models: raise RuntimeError(f"model order mismatch: {key}")
            raw[i, j] = np.asarray(row["all_rm_scores"], dtype=float)
    if not np.isfinite(raw).all(): raise RuntimeError("nonfinite score")
    lo, hi = raw.min(2, keepdims=True), raw.max(2, keepdims=True)
    norm = np.where(hi == lo, .5, (raw-lo)/(hi-lo)); avg = norm.mean(1); worst = norm.min(1)
    rng = np.random.default_rng(args.seed); ix = rng.integers(0, len(ids), size=(args.bootstrap, len(ids)))
    output = []
    for m, name in enumerate(models):
        if name not in W2 and name != "ronpo_os_confirmatory": continue
        item = {"model": name, "display_name": DISPLAY.get(name, name), "helpfulness_norm": float(norm[:,0,m].mean()), "harmlessness_norm": float(norm[:,1,m].mean()), "avg": float(avg[:,m].mean()), "worst": float(worst[:,m].mean()), "worst_ci95": ci(worst[ix,m].mean(1)), "helpfulness_raw": float(raw[:,0,m].mean()), "harmlessness_raw": float(raw[:,1,m].mean())}
        output.append(item)
    output.sort(key=lambda r: (-r["worst"], r["model"]))
    payload = {"status": "complete", "diagnostic_only": True, "normalization": "per-prompt minmax across Base, W1, and W2 eligible models", "records": len(ids), "all_eligible_models": models, "ranking": output, "bootstrap": {"resamples": args.bootstrap, "seed": args.seed, "unit": "prompt"}, "spent_sealed_split_touched": False}
    (args.output_dir / "w2_model_summary.json").write_text(json.dumps(payload, indent=2)+"\n", encoding="utf-8")
    md = ["# Diagnostic estimator ablation", "", "These rows are non-confirmatory and cannot replace the preregistered W1 headline result.", "", "| Method | Help. | Harmless | Avg | Worst (95% CI) |", "|---|---:|---:|---:|---:|"]
    for r in output: md.append(f"| {r['display_name']} | {r['helpfulness_norm']:.3f} | {r['harmlessness_norm']:.3f} | {r['avg']:.3f} | {r['worst']:.3f} [{r['worst_ci95'][0]:.3f}, {r['worst_ci95'][1]:.3f}] |")
    (args.output_dir / "CURVE.md").write_text("\n".join(md)+"\n", encoding="utf-8")
    tex = ["% Generated by build_w2_ablation.py; all rows are diagnostic/non-confirmatory.", "\\begin{table}[t]", "\\centering", "\\scriptsize", "\\begin{tabular}{lrrrr}", "\\toprule", "Method & Help. & Harmless & Avg & Worst " + r"\\", "\\midrule"]
    for r in output:
        tex.append(f"{r['display_name']} & {r['helpfulness_norm']:.3f} & {r['harmlessness_norm']:.3f} & {r['avg']:.3f} & {r['worst']:.3f} [{r['worst_ci95'][0]:.3f}, {r['worst_ci95'][1]:.3f}] " + r"\\")
    tex += ["\\bottomrule", "\\end{tabular}", "\\caption{Diagnostic SafeRLHF 8B estimator ablation. These rows were not used to select the preregistered W1 headline arm.}", "\\label{tab:saferlhf-estimator-ablation-8b}", "\\end{table}", ""]
    (args.output_dir / "table_estimator_ablation_8b.tex").write_text("\n".join(tex), encoding="utf-8")


if __name__ == "__main__":
    main()
