#!/usr/bin/env python3
"""Render submission tables without modifying earlier single-seed snapshots."""
from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parents[1]


def rows(name):
    with (ROOT / 'data' / name).open(newline='') as f:
        return list(csv.DictReader(f))


def num(value, digits=None):
    if not str(value).strip():
        return r'\pending'
    value = f'{float(value):.{digits}f}' if digits is not None else value
    return '$' + str(value) + '$'


def spread(mean, variation, digits=4):
    if not mean.strip():
        return r'\pending'
    if not variation.strip():
        return num(mean, digits)
    return f'${float(mean):.{digits}f}\\pm{float(variation):.{digits}f}$'


def table(name, spec, headers, body):
    lines = [r'% Generated by scripts/render_new_main_tables.py; edit data/*.csv.',
             r'\begin{tabular}{' + spec + '}', r'\toprule',
             ' & '.join(headers) + r'\\', r'\midrule']
    for row in body:
        lines.append(row if isinstance(row, str) else ' & '.join(row) + r'\\')
    lines += [r'\bottomrule', r'\end{tabular}', '']
    (ROOT / 'generated' / name).write_text('\n'.join(lines))


def main():
    data = rows('uf_objectives.csv')
    table('uf_objectives_main.tex', 'lrrrrrrrr',
          ['Method', r'$N_{\rm train}$', 'Seeds', r'$N_{\rm eval}$', 'IF', 'Truth', 'Honesty', 'Help',
           r'$\min_k\Delta_k$'],
          [[r['method_tex'], num(r['policy_train_prompts']), num(r['completed_seeds']), num(r['eval_prompts'])] +
           [num(r[k], 3) for k in ['if_wr', 'truth_wr', 'honesty_wr', 'help_wr', 'min_delta']]
           for r in data])
    data = rows('new_capability_results.csv')
    body = []
    current_dataset = None
    for r in data:
        if current_dataset != r['dataset']:
            if current_dataset is not None:
                body.append(r'\midrule')
            current_dataset = r['dataset']
            # Describe the block by what its rows actually contain. A single
            # reused base row must not make a block of unmeasured policy rows
            # read as a completed three-seed study.
            block = [q for q in data if q['dataset'] == current_dataset]
            policy = [q for q in block if q['policy_train_prompts'] not in ('', '0')]
            if all(q['status'] == 'planned' for q in policy):
                suffix = ('base measurements reused; policy rows planned, no measurements'
                          if any(q['status'] != 'planned' for q in block)
                          else 'planned; no measurements')
            else:
                suffix = 'reported three-seed study'
            body.append(r'\multicolumn{9}{l}{\textit{' + current_dataset + ': ' + suffix + r'}}\\')
        body.append([r['method_tex'], spread(r['ifeval_strict_prompt'], r['ifeval_seed_sd'], 3)] +
                    [num(r[k], 3) for k in ['gsm8k_em', 'mmlu_accuracy', 'harmbench_harmful',
                     'xstest_safe_refusal', 'alpaca_local_wr', 'arena_hard_local_wr',
                     'arena_creative_local_wr']])
    table('new_capability_main.tex', 'lrrrrrrrr',
          ['Method', 'IFEval', 'GSM8K', 'MMLU', r'HB$\downarrow$', r'XS$\downarrow$',
           'Alpaca', 'AH-hard', 'AH-creat.'], body)
    data = rows('safe_three_seed_results.csv')
    table('safe_three_seed.tex', 'lrrrr',
          ['Family', 'Seeds', r'nMSE$\downarrow$', r'Sign$\uparrow$', r'$\min_k s_k\uparrow$'],
          [[r['method_tex'], num(r['n_seeds']),
            spread(r['nmse_mean'], r['nmse_reported_spread']),
            spread(r['sign_mean'], r['sign_reported_spread']),
            spread(r['worst_surplus_mean'], r['worst_surplus_reported_spread'])] for r in data])
    data = rows('aggregation_policy_pairs.csv')
    body = []
    for seed in sorted({r['seed'] for r in data}, key=int):
        entry = [num(seed)]
        for criterion in ['help', 'safe']:
            r = next(x for x in data if x['seed'] == seed and x['criterion'] == criterion)
            entry += [num(r['delta_nash_minus_util']),
                      '$[' + r['ci_low'] + ',' + r['ci_high'] + ']$']
        body.append(entry)
    table('aggregation_policy_pairs.tex', 'lrrrr',
          ['Seed', r'$\Delta s_{\rm help}$', 'Reported CI', r'$\Delta s_{\rm safe}$', 'Reported CI'], body)


if __name__ == '__main__':
    main()
