#!/usr/bin/env python3
r"""Regenerate editable LaTeX tables from the accompanying CSV files.

Blank cells remain unmeasured (\pending). Do not insert literature numbers from
unmatched models, evaluators or decoding protocols into these rows.
"""
from pathlib import Path
import csv

ROOT = Path(__file__).resolve().parents[1]

def rows(name):
    with (ROOT/'data'/name).open(newline='') as f:
        return list(csv.DictReader(f))

def value(x):
    if not x.strip():
        return r'\pending'
    if x.startswith('\\'):
        return x
    return '$'+x+'$'

def table(name, spec, headers, body):
    lines = [r'% Generated by scripts/render_tables.py; edit data/*.csv.',
             r'\begin{tabular}{'+spec+'}', r'\toprule',
             ' & '.join(headers)+r'\\', r'\midrule']
    lines += [' & '.join(row)+r'\\' for row in body]
    lines += [r'\bottomrule', r'\end{tabular}', '']
    (ROOT/'generated'/name).write_text('\n'.join(lines))

def main():
    a=rows('alignment_results.csv')
    table('alignment_main.tex','lrrrr',
          ['Method','Updates',r'$s_{\rm help}\uparrow$',r'$s_{\rm safe}\uparrow$',r'$\min_k s_k\uparrow$'],
          [[x['method_tex']]+[value(x[k]) for k in ['updates','help_surplus','safe_surplus','min_surplus']] for x in a])
    c=rows('capability_results.csv')
    table('capability_main.tex','lrrrrrrrr',
          ['Method','IFEval','GSM8K',r'Harm$\downarrow$',r'Refusal$\downarrow$',
           'Alpaca','AH-hard','AH-creative','Tokens'],
          [[x['method_tex']]+[value(x[k]) for k in ['ifeval_strict_prompt','gsm8k_em','harmbench_harmful',
           'xstest_safe_refusal','alpaca_local_wr','arena_hard_local_wr','arena_creative_local_wr','alpaca_median_tokens']] for x in c])
    r=rows('realization_results.csv')
    table('realization_main.tex','lrrrrrr',
          ['Projection','Horizon','nMSE', 'Sign','Pearson',r'Pool KL$\downarrow$','GPU-h'],
          [[x['method_tex']]+[value(x[k]) for k in ['horizon','nmse','sign','pearson','pool_forward_kl','gpu_hours']] for x in r])
    p=rows('pool_drift_results.csv')
    def correlation_ci(x):
        if not x['pearson'].strip():
            return r'\pending'
        return '$'+x['pearson']+r'\;['+x['pearson_ci_low']+','+x['pearson_ci_high']+']$'
    table('pool_drift_full.tex','lrrrrr',
          ['Policy','Pearson [clustered CI]',r'$D_{\rm KL}\downarrow$',
           r'KL improvement$\uparrow$','Top-1','Argmax mass'],
          [[x['method_tex'],correlation_ci(x)]+[value(x[k]) for k in
           ['forward_kl','kl_improvement_reported','target_top1_agreement','target_argmax_mass']] for x in p])
    d=rows('downstream_reported_snapshot.csv')
    table('downstream_reported_snapshot.tex','lrrrrrrr',
          ['Policy',r'$\min_k s_k$','IFEval','GSM8K',r'Harm$\downarrow$',
           'Alpaca','Arena (unassigned)','Tokens (unassigned)'],
          [[x['method_tex']]+[value(x[k]) for k in ['worst_surplus','ifeval_reported',
           'gsm8k_em','harmbench_harmful','alpaca_local_wr','arena_unassigned_local_wr',
           'unassigned_median_tokens']] for x in d])
    g=rows('aggregation_targets.csv')
    table('aggregation_targets.tex','lr',['Diagnostic','Value'],
          [[x['metric_tex'],value(x['value'])] for x in g])
    table('evaluation_contract.tex','lp{8.9cm}', ['Set / target count','Metric and completion contract'], [
          ['SafeRLHF / 1000','Teacher-defined objective values; comparator and disagreement hashes; greedy and stochastic evaluations kept separate.'],
          ['IFEval / 541','Official strict prompt and instruction accuracy; loose scores secondary. Verify the reported strict column against evaluator output.'],
          ['GSM8K / 1319','Fixed zero-shot-CoT prompt and answer extractor; exact match and parse-failure count.'],
          ['HarmBench / text test','Report actual category counts and classifier version. Use category-specific hashing where required.'],
          ['XSTest / 250 safe, 200 unsafe','Benign refusal and unsafe-request handling separately; report classifier or blinded manual assessment.'],
          ['Alpaca / 805','Same-prompt local reward-model win rate versus base, ties half; response length from the same prompt set.'],
          ['Arena / 500 hard, 250 creative','Report subset-specific local proxy win rates; an unassigned aggregate does not populate these columns.'],
          ['MT-Bench / 80','Optional two-turn responses; no official score without the stated judging protocol.']])

if __name__=='__main__':
    main()
    from render_new_main_tables import main as render_new_main
    render_new_main()
