#!/usr/bin/env python3
"""Render the display-only Stage-4 SafeRLHF appendix table from frozen JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


DISPLAY_NAMES = {
    "ronpo_os_stage4": "RONPO (OS)",
    "ht_mnpo_helpfulness_stage4": "HT-MNPO (help.)",
    "ht_mnpo_harmless_stage4": "HT-MNPO (harml.)",
    "inpo_avg_stage4": "INPO-avg",
    "sppo_avg_stage4": "SPPO-avg",
    "simpo_stage4": "SimPO",
    "ipo_stage4": "IPO",
    "dpo_stage4": "DPO",
    "base": "Base",
}
OMITTED = "ronpo_topmass_stage4"
METRICS = (
    "helpfulness_norm",
    "harmlessness_norm",
    "mean_objective_norm_score",
    "mean_prompt_worst_norm_score",
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def decorate(value: float, metric: str, rows: list[dict]) -> str:
    ordered = sorted((float(row[metric]) for row in rows), reverse=True)
    text = f"{value:.3f}"
    if value == ordered[0]:
        return f"\\textbf{{{text}}}"
    if value == ordered[1]:
        return f"\\underline{{{text}}}"
    return text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument("--tex", type=Path, required=True)
    parser.add_argument("--audit", type=Path, required=True)
    args = parser.parse_args()

    payload = json.loads(args.summary.read_text(encoding="utf-8"))
    ranking = payload["ranking"]
    by_model = {row["model"]: row for row in ranking}
    expected = set(DISPLAY_NAMES) | {OMITTED}
    observed = set(by_model)
    if expected != observed:
        raise RuntimeError(
            f"unexpected Stage-4 model set: missing={expected-observed}, extra={observed-expected}"
        )
    if any(int(row["records"]) != 1000 for row in ranking):
        raise RuntimeError("Stage-4 table requires exactly 1,000 records for every policy")

    rows = [row for row in ranking if row["model"] != OMITTED]
    rows.sort(key=lambda row: (-float(row["mean_prompt_worst_norm_score"]), row["model"]))
    lines = [
        "% Auto-generated by analysis/p8_stage4_fresh_default_test_20260718/build_appendix_stage4_table.py",
        "% Do not hand-edit numbers; source: ranked_validation_summary.json.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{6pt}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Method & Help. & Harmless. & Avg & Worst " + r"\\",
        "\\midrule",
    ]
    for row in rows:
        name = DISPLAY_NAMES[row["model"]]
        cells = [decorate(float(row[metric]), metric, rows) for metric in METRICS]
        lines.append(f"{name} & " + " & ".join(cells) + " " + r"\\")
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{\\textbf{Stage-4 SafeRLHF robustness results.} This matched fourth continuation uses the same format as Table~\\ref{tab:saferlhf-robust}. Helpfulness (Beaver reward) and harmlessness (negated Beaver cost) are min--max normalized per prompt over the frozen Stage-4 eligible-policy pool; \\emph{Avg} and \\emph{Worst} are the per-prompt mean and minimum of the two normalized objectives, averaged over the prompt-disjoint 1{,}000-prompt SafeRLHF default-test panel. Best in bold, second best underlined. RONPO top-mass is omitted from display; no model selection or re-normalization was performed for this appendix table. Every displayed policy passed the generation stability gate.}",
        "\\label{tab:saferlhf-stage4-robust}",
        "\\end{table}",
        "",
    ])
    args.tex.parent.mkdir(parents=True, exist_ok=True)
    args.tex.write_text("\n".join(lines), encoding="utf-8")
    audit = {
        "status": "generated",
        "source_summary": str(args.summary),
        "source_summary_sha256": digest(args.summary),
        "source_scope": payload.get("scope"),
        "records_per_policy": 1000,
        "normalization": "frozen original Stage-4 eligible-policy pool; display-only top-mass omission",
        "omitted_display_row": OMITTED,
        "displayed_models": [row["model"] for row in rows],
        "values": [{metric: row[metric] for metric in ("model",) + METRICS} for row in rows],
        "table_sha256": digest(args.tex),
    }
    args.audit.write_text(json.dumps(audit, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
